### ISSUE TITLE
Account onboarding links expire can't reauth in v3

### ISSUE THREAD

**Issue by christophersjchow** [stripe/stripe-mirakl-connector#101]
We're experiencing issues with onboarding links now expiring. From what I can tell the onboarding links are still being generated with a `refresh_url` of `https://stripe-mirakl-connector-host/api/onboarding` with the refresh token being passed in as a query param.

However this route was removed in v3? So are onboarding links now only temporary? From what I can tell the lifetime of an onboarding link now is only 5 minutes

**Comment by christophersjchow** [comment]
Ok I've narrowed it down to the request the connector makes to refresh the link. For some reason the call to Stripe from the connector to refresh the link fails as the `refresh_url` that gets passed to Stripe uses `http` and not `https`

<img width="630" alt="Screen Shot 2022-03-25 at 6 11 39 pm" src="https://user-images.githubusercontent.com/47544496/160072172-c8919ce3-db65-4347-b4eb-35545a1329f3.png">
.

**Comment by christophersjchow** [comment]
Note the initial onboarding link generated when a shop is updated works fine until it expires. It also has the correct https refresh url. It's just after the link expires the subsequent regeneration fails.

**Comment by youssef-stripe** [comment]
This is fixed in v3.0.2. Thanks for reporting this and for your help fixing it.

For future reference, proxy users must set the `TRUSTED_PROXIES` environment variable, see [How to Configure Symfony to Work behind a Load Balancer or a Reverse Proxy](https://symfony.com/doc/4.4/deployment/proxies.html).
