### ISSUE TITLE
Disabling capture for staging environment?

### ISSUE THREAD

**Issue by TechyChap** [stripe/stripe-mirakl-connector#103]
On our staging environment I'm getting a large number of messages of the following form:

"Could not capture Stripe Charge: This PaymentIntent could not be captured because it has already been captured.."
I suspect this is because our testers are reusing the same payment for multiple tests.

Looking at the flow I see that the capture process is decoupled from the job via a message.
https://stripe.com/docs/plugins/mirakl/payments#payment-validation

Is it possible to reroute or disable the cancel_pending_payment queue?
Or is it a case of disabling in supervisord.conf

**Comment by youssef-stripe** [comment]
There's no configuration to enable/disable this flow. The connector relies on the commercial order ID being set in the payment's metadata or not, i.e. don't set it if you don't want to use the validation job.

You could indeed disable the consumer in supervisord.conf but this won't prevent the messages from being dispatched and they will eventually pile up in the queue.

It would be cleaner to comment out the [dispatch instruction](https://github.com/stripe/stripe-mirakl-connector/blob/master/src/Command/PaymentValidationCommand.php#L166) or just add an early `return;` in the [capture](https://github.com/stripe/stripe-mirakl-connector/blob/master/src/Handler/CapturePendingPaymentHandler.php#L36-L59) / [cancel](https://github.com/stripe/stripe-mirakl-connector/blob/master/src/Handler/CancelPendingPaymentHandler.php#L37-L55) handlers.

**Comment by TechyChap** [comment]
On review. This is not just our test environment. We will be capturing before submitting the order to Mirakl so will always have the charge in the wrong state as far as the capture is concerned.

Would something like this work in CapturePendingPaymentHandler.php


```
    public function __invoke(CapturePendingPaymentMessage $message)
    {
        $paymentMapping = $this->paymentMappingRepository->findOneBy([
            'id' => $message->getPaymentMappingId(),
        ]);
        assert(null !== $paymentMapping);
        assert(PaymentMapping::TO_CAPTURE === $paymentMapping->getStatus());

        try {
            $this->stripeClient->capturePayment(
                $paymentMapping->getStripeChargeId(),
                $message->getAmount()
            );

            $paymentMapping->capture();
            $this->paymentMappingRepository->flush();
        } catch (ApiErrorException $e) {
                       if ($e->getStripeCode() == 'payment_intent_unexpected_state' && str_contains($e->getMessage(), 'already been captured')) {
				$paymentMapping->capture();
				$this->paymentMappingRepository->flush();
				return;
			}
						
            $this->logger->error(sprintf('Could not capture Stripe Charge: %s.', $e->getMessage()), [
                'chargeId' => $paymentMapping->getStripeChargeId(),
                'amount' => $message->getAmount(),
                'stripeErrorCode' => $e->getStripeCode(),
            ]);
        }
    }
```
