### ISSUE TITLE
Out of Memory Error running the debit job

### ISSUE THREAD

**Issue by TechyChap** [stripe/stripe-mirakl-connector#104]
We are getting an out of memory error, when processing the pending debit job.

php /var/www/bin/console connector:validate:pending-debit -q > /dev/null 2>&1

Fatal Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes)
Symfony\Component\ErrorHandler\Error\OutOfMemoryError
/var/www/src/Service/MiraklClient.php:187

Is this a virtual machine memory setting or perhaps a memory setting for Symfory and/or some webserver?
The allowed memory size is 16384 * 8192 which seems quite specific.

Any advice on diagnosing and/or fixing this?

**Comment by TechyChap** [comment]
Ran this via the console.

php /var/www/bin/console connector:validate:pending-debit -v

Cannot load Zend OPcache - it was already loaded
[01-Apr-2022 10:41:06 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in /var/www/src/Service/MiraklClient.php on line 187

[01-Apr-2022 10:41:06 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) in /var/www/vendor/composer/ClassLoader.php on line 571

**Comment by TechyChap** [comment]
Rebooted the server and still getting the same error

**Comment by youssef-stripe** [comment]
This could be related to #103. Can you try updating payment_mapping.status to "captured" for test payments you are done using?

This workflow isn't supposed to stack too many entities to process and isn't optimized in that way. How many "to_capture" payments do you have in the payment_mapping table?

**Comment by TechyChap** [comment]
select count(*) from payment_mapping;

 count 
-------
 51616

**Comment by TechyChap** [comment]
symfony=> select count(*) from payment_mapping;
 count 
-------
 51616

**Comment by youssef-stripe** [comment]
And if you add `where status='to_capture'`?

**Comment by TechyChap** [comment]
Should be possible to throttle this DB call with something like:

```
public function findToCapturePayments(): array
    {
        return $this->mapByMiraklCommercialOrderId($this->findBy([
            'status' => PaymentMapping::TO_CAPTURE
        ])->setMaxResults(1000));
    }
```

**Comment by youssef-stripe** [comment]
This would result in payments > 1000 being stuck until some of the first 1000 are captured. A better solution would be to process batches of X (e.g. 100) payments on a loop so we don't store all 51k payments (in this case) in memory while the process is running.

**Comment by youssef-stripe** [comment]
We'll add this to our backlog. In the meantime, and in a nominal case, payments shouldn't stack fast enough to reach OOM exceptions.
