### ISSUE TITLE
Refunds stay pending

### ISSUE THREAD

**Issue by TechyChap** [stripe/stripe-mirakl-connector#106]
What we are seeing:

Create an order in Mirakl
Order is moved to the "Shipping" state by shop

symfony=> select * from payment_mapping where mirakl_commercial_order_id = 'M11760039';
 id  | mirakl_commercial_order_id |      stripe_charge_id       |  status  |  creation_datetime  | modification_datetime | stripe_amount 
-----+----------------------------+-----------------------------+----------+---------------------+-----------------------+---------------
 362 | M11760039                  | ch_3KvgBrC3Am8Jma0p1wRoFU9U | captured | 2022-05-04 11:16:25 | 2022-05-04 11:16:28   |          6900

Refund is created in Mirakl dashboard.
Payment Refund Job runs 
https://stripe.com/docs/plugins/mirakl/reference#payment-refund

We can see that the refund is created in Stripe test dashboard with status of success.

{
  "charge": "ch_3KvgBrC3Am8Jma0p1wRoFU9U",
  "amount": "5000",
  "metadata": {
    "miraklRefundId": "1158",
    "pluginName": "MiraklConnector",
    "pluginVersion": "2.1.4"
  }
}

{
  "id": "re_3KvgBrC3Am8Jma0p1xHrZ5qb",
  "object": "refund",
  "amount": 5000,
  "balance_transaction": "txn_3KvgBrC3Am8Jma0p1f8xfxTh",
  "charge": ["ch_3KvgBrC3Am8Jma0p1wRoFU9U"](https://dashboard.stripe.com/test/payments/ch_3KvgBrC3Am8Jma0p1wRoFU9U),
  "created": 1651664826,
  "currency": "gbp",
  "metadata": {
    "miraklRefundId": "1158",
    "pluginName": "MiraklConnector",
    "pluginVersion": "2.1.4"
  },
  "payment_intent": ["pi_3KvgBrC3Am8Jma0p10MAN2Wh"](https://dashboard.stripe.com/test/payments/pi_3KvgBrC3Am8Jma0p10MAN2Wh),
  "reason": null,
  "receipt_number": null,
  "source_transfer_reversal": null,
  "status": "succeeded",
  "transfer_reversal": null
}

but it looks like the PA02 call never sets the refund to move it from awaiting refund into refunded.

symfony=> select * from stripe_refund where mirakl_commercial_order_id = 'M11760039';
 id | amount | currency | mirakl_refund_id | mirakl_order_id | stripe_refund_id |     status     | status_reason | mirakl_validation_time |  creation_datetime  | modification_datetime | mirakl_order_line_id |  
     transaction_id        |         type         | mirakl_commercial_order_id 
----+--------+----------+------------------+-----------------+------------------+----------------+---------------+------------------------+---------------------+-----------------------+----------------------+--
---------------------------+----------------------+----------------------------
 42 |   5000 | gbp      | 1158             | M11760039-B     |                  | REFUND_PENDING |               |                        | 2022-05-04 11:47:04 | 2022-05-04 11:47:04   | M11760039-B-1        | c
h_3KvgBrC3Am8Jma0p1wRoFU9U | REFUND_PRODUCT_ORDER | M11760039

**Comment by TechyChap** [comment]
We are also seeing in our logs:

Transfer on hold: Refund 1158 has yet to be validated

**Comment by youssef-stripe** [comment]
PA02 is most likely returning an error. Can you check the logs captured by [src/Handler/ProcessRefundHandler.php#L99-L105](https://github.com/stripe/stripe-mirakl-connector/blob/master/src/Handler/ProcessRefundHandler.php#L99-L105)?

**Comment by TechyChap** [comment]
Thanks Youssef, I don't seem to be able to find that anywhere in our logs and a number of refunds have processed without error. It could have been an issue with our UAT processes. If it re-occurs will look into this again.

For future help, for the default docker configuration where would the logs for ProcessRefundHander end up? I just want to make sure they are getting processed and sent on to our logging system.

**Comment by youssef-stripe** [comment]
By default, the logs are sent to the console which docker allows you to access via the [docker-compose logs](https://docs.docker.com/compose/reference/logs/) command.
You can change this here in the [filebeat.yml](https://github.com/stripe/stripe-mirakl-connector/blob/master/examples/docker/app/config/filebeat.yml#L176-L185) configuration file.
