### ISSUE TITLE
Mismatch of Postgres Versions

### ISSUE THREAD

**Issue by TechyChap** [stripe/stripe-mirakl-connector#107]
When logged onto the App server and connecting using PSQL to the DB server. We tried to see the columns of the stripe refund table using the \d command. Which is apparently due to a mismatch of versions.

```
symfony=> \d stripe_refund
ERROR:  column c.relhasoids does not exist
LINE 1: ...riggers, c.relrowsecurity, c.relforcerowsecurity, c.relhasoi...
                                                             ^

```

Our postgress server is version 13.4. The client still seems to be 11. I tried manually upgrading the client with apt-get upgrade postgressql and it said I was on the latest.

Is version 13.4 officially supported by this connector?
What is the process for upgrade?

**Comment by youssef-stripe** [comment]
Did you try updating the server version in the [doctrine config file](https://github.com/stripe/stripe-mirakl-connector/blob/master/config/packages/doctrine.yaml#L5)?
