### ISSUE TITLE
Health check route

### ISSUE THREAD

**Issue by christophersjchow** [stripe/stripe-mirakl-connector#32]
Is there a path that can be used for health checking say with Pingdom? Or could one of the existing routes be used?

**Comment by youssef-stripe** [comment]
Hi @christophersjchow,

There's no specific health check endpoint. You can use GET /api/mappings which will confirm that both the PHP application is running and that the database is also reachable and running.

I'll keep this feedback under advisement for our future developments. In the meantime, we also welcome [contributions](https://github.com/stripe/stripe-mirakl-connector#contributing-to-the-application) if you feel like building this.

Thanks
Youssef
