### ISSUE TITLE
Restricted key permission for Stripe client secret

### ISSUE THREAD

**Issue by christophersjchow** [stripe/stripe-mirakl-connector#33]
What are the specific permissions the `STRIPE_CLIENT_SECRET` requires if we are to use a restricted key? It would be great if the docs were updated here https://stripe.com/docs/plugins/mirakl/configuration to specify the permissions required, similar to how the webhook configs specify the specific events.

**Comment by youssef-stripe** [comment]
Hi @christophersjchow,

Thanks for the suggestion. At the moment the connector has been tested with a secret key (not restricted). We will review this and let you know if using a restricted key is possible and what permissions would have to be used.

**Comment by christophersjchow** [comment]
@youssef-stripe Thanks. To add some info, I tried to execute onboarding with a restricted key with "All Connect resources" set to "write".

Unfortunately this did not work despite what I observe as the correct permissions.

```
[2020-11-19 10:28:59] app.INFO: [Stripe API] Call to \Stripe\Account::update {"stripeUserId":"acct_xxxxx"} []
[2020-11-19 10:28:59] app.ERROR: Could not process return from Stripe {"code":null,"description":"You passed a restricted API key with the Stripe-Account header, but the restricted API key does not have any Connect permissions."} []
```

**Comment by youssef-stripe** [comment]
After further investigation, there is indeed a limitation to Restricted Account Keys today, as they can't be used to create or update connected accounts. "All Connect resources" does not include Accounts.

We will update the docs to confirm that using a RAK is not an option today.

**Comment by youssef-stripe** [comment]
The docs have been updated to confirm that it is not possible to use a restricted key today: https://stripe.com/docs/plugins/mirakl/configuration#general-settings
> Your Stripe API secret key available in your API keys settings. We recommend creating a specific API key for the connector. Restricted keys are not supported.


Thanks for raising this.
