### ISSUE TITLE
Onboarding Stripe Connect link not being replaced by Login link

### ISSUE THREAD

**Issue by christophersjchow** [stripe/stripe-mirakl-connector#34]
I've managed to get the connector deployed and handling the onboarding process for sellers. However I'm unable to observe the behaviour where the connector replaces the onboarding link on the Mirakl Store's custom field `stripe-url` with the link to login to the Stripe Connect Express dashboard as described here https://stripe.com/docs/plugins/mirakl/onboarding-sellers in step 6.

![](https://stripe.com/img/docs/mirakl/seller-account-initiation.svg)

I've tried looking at the code but can't seem to find a place where the Connector does a `PATCH` call to the Mirakl API to update the `stripe-url`? My understanding is that this should be called after Stripe redirects back to the connector after onboarding is complete here but there doesn't seem to anything relating to updating the shop in Mirakl. https://github.com/stripe/stripe-mirakl-connector/blob/231ff68039900aa41f139a60d88de0ba40826ddb/src/Controller/CreateMappingFromStripe.php#L121

Additionally it seems there isn't any code to create the login link as per the Stripe docs here: https://stripe.com/docs/api/account/create_login_link

Is this functionality not implemented and are the docs wrong or am I missing something?

**Comment by youssef-stripe** [comment]
The step 6 is a bit misleading as what actually happens in that at the end of the process, the account is updated, triggering an event handled in the Seller account update workflow: https://stripe.com/docs/plugins/mirakl/onboarding-sellers#seller-account-update

Did you set up the sellers webhook correctly? See https://stripe.com/docs/plugins/mirakl/configuration#add-a-stripe-webhook-endpoint-for-connected-accounts

As for generating the login link, you can do it via the Stripe API using the docs you mentioned. The connector only supports generating an onboarding link.

**Comment by christophersjchow** [comment]
> As for generating the login link, you can do it via the Stripe API using the docs you mentioned. The connector only supports generating an onboarding link.

Does this mean the docs linked above are inaccurate? As it explicitly says this this as step 6:

> The onboarding link is replaced with a link to login to their Express dashboard.

**Comment by youssef-stripe** [comment]
The login link is generated by the connector upon receiving the account.updated event. This event is triggered at the end of the onboarding process.

Regarding the docs, you are correct, thanks for flagging. We will update step 6 of the account initiation workflow and replace it with "The payout frequency is set to manual. This triggers a [seller account update](https://stripe.com/docs/plugins/mirakl/onboarding-sellers#seller-account-update).".

**Comment by youssef-stripe** [comment]
The docs have been updated accordingly: https://stripe.com/docs/plugins/mirakl/onboarding-sellers#seller-account-initiation

Thanks again for flagging!
