### ISSUE TITLE
Does the connector support the PAY_ON_ACCEPTANCE workflow?

### ISSUE THREAD

**Issue by christophersjchow** [stripe/stripe-mirakl-connector#39]
We're trying to get the connector to capture payments for orders that have been accepted by our sellers. However it looks like the current handler filters `WAITING_DEBIT_PAYMENT` statuses.

I'm not completely sure of the impact of adding this to status to this set of statuses: https://github.com/stripe/stripe-mirakl-connector/blob/7bbe22a5d44326a3ed5964abd681633be28990c2/src/Command/ValidatePendingDebitCommand.php#L22-L23

Any insight would be appreciated.

**Comment by youssef-stripe** [comment]
@christophersjchow the capture only occurs when all the logistical orders of a commercial orders have been accepted or refused. The authorization is valid for 7 days. By default all sellers must accept their orders within 5 days.

We built the workflow this way because Stripe doesn't support multi-capture yet.

Did you test the workflow? In your test, did you leave any logistical order in pending acceptance?

**Comment by youssef-stripe** [comment]
@christophersjchow: as mentioned above, this is the expected workflow. I'm closing this issue but feel free to reopen should you have any follow-up questions.

**Comment by christophersjchow** [comment]
@youssef-stripe My question wasn't about acceptance or rejection. (I'm unable to reopen the issue but can comment). My question was in relation to the fact that Mirakl has 3 types of payment workflows for handling payments specifically:

- Pay on Acceptance
- Pay on Delivery
- Pay on Due Date

Each of these different workflows affects the status of logistical orders after they are accepted or refused. Specifically we are using the "Pay on Acceptance" workflow and that means after an order is accepted by a seller it moves into a `WAITING_DEBIT_PAYMENT` status, which is not in the array of statuses that the above handler processes. My question then is should this status actually be in that list in order so this workflow can be supported?

The docs on the connector do not indicate what Payment workflows are supported. If it helps I'm happy to loop in our Stripe Enterprise Account Representative to engage here.

**Comment by youssef-stripe** [comment]
The payment validation workflow uses PA11:
>List pending order debits in PAY_ON_ACCEPTANCE workflow and order status is WAITING_DEBIT_PAYMENT.
=> https://github.com/stripe/stripe-mirakl-connector/blob/master/src/Command/ValidatePendingDebitCommand.php#L77

This means that the validation/capture workflow only supports PAY_ON_ACCEPTANCE.
For PAY_ON_DELIVERY and PAY_ON_DUE_DATE, the operator would have to handle the validation (PA01) and capture on their side and the connector can still handle the payment split and payout to the sellers.

We will clarify this in the docs.

**Comment by youssef-stripe** [comment]
> The docs on the connector do not indicate what Payment workflows are supported. If it helps I'm happy to loop in our Stripe Enterprise Account Representative to engage here.

We added a section in the documentation with guidelines for each workflow: https://stripe.com/docs/plugins/mirakl/payments#payment-creation
