### ISSUE TITLE
Missing rename of sequence after deprecating payment intents

### ISSUE THREAD

**Issue by christophersjchow** [stripe/stripe-mirakl-connector#44]
In #38, the of the table in this migration
https://github.com/stripe/stripe-mirakl-connector/pull/38/files#diff-d503ebb877eadf180c5f409f1391991227ba7ad62d2fae158b602ee413ec668eR1 failed to rename the `stripe_payment_id_seq` sequence.

**Comment by youssef-stripe** [comment]
Thanks for flagging @christophersjchow. This is fixed in #45.
