### ISSUE TITLE
"Invalid signature" after upgrade v1.2.0 -> v1.2.4 or v1.2.0 -> v1.2.7

### ISSUE THREAD

**Issue by eBusEntwHOFM** [stripe/stripe-mirakl-connector#47]
Hi folks,

unfortunately we become `Invalid signature` error after upgrade v.1.2.0 to v1.2.4. To upgrade v.1.2.0 to v.1.2.7 doesn't help either.

**Screenshot at Stripe:**

![Screenshot 2021-01-11 at 08 23 24](https://user-images.githubusercontent.com/72541157/104155364-55627a00-53e7-11eb-953d-e168d43daa64.png)

**Log message at stripe-mirakl-connector:**

```
Invalid signature [] []
```

Best regards

**Comment by youssef-stripe** [comment]
Thanks for flagging. Minor and patch upgrades are meant to be fully backward compatible so we will fix this as soon as possible in the next minor release.

In the meantime, try setting STRIPE_SELLERS_WEBHOOK_SECRET to the webhook secret of the endpoint sending account.updated messages. This should fix your issue.

**Comment by youssef-stripe** [comment]
@eBusEntwHOFM looking at the code and trying to reproduce, we do not seem to find any regression with this part. We are still investigating but could you please double check that either `STRIPE_SELLERS_WEBHOOK_SECRET` or `STRIPE_WEBHOOK_SECRET` is set with the right webhook secret?

**Comment by eBusEntwHOFM** [comment]
Thanks @yasha-stripe, that was the issue, I've replaced `STRIPE_WEBHOOK_SECRET` with `STRIPE_SELLERS_WEBHOOK_SECRET` and now it works.
