### ISSUE TITLE
process-refund stucks

### ISSUE THREAD

**Issue by eBusEntwHOFM** [stripe/stripe-mirakl-connector#54]
`process-refund` stucks if there are `> 9` refunds which couldn't be processed because of some errors.

If I correctly understood the code, it happends because smc [doesn't repect](https://github.com/stripe/stripe-mirakl-connector/blob/c92955f84d59ac0bf14477b0aeadf5ede46b8770/src/Utils/MiraklClient.php#L85) `total_count` returned by [PA12](https://help.mirakl.net/help/api-doc/operator/mmp.html#PA12) and doesn't [use `max` and `offset`](https://help.mirakl.net/help/api-doc/operator/mmp.html#offset-pagination) to process next items.

Best regards
-a

**Comment by youssef-stripe** [comment]
@eBusEntwHOFM: yes, this is something that we are improving in the next major release #49, i.e. we added support for pagination and better backlog handling when items stack up.

This v2 beta still has some issues to be fixed and I wouldn't recommend using it in production until we release some fixes which are planned in the next couple of days.
After then, I would still recommend in upgrade in test mode first to make sure the new changes fit with your environment.

**Comment by youssef-stripe** [comment]
@eBusEntwHOFM we fixed the critical issues with the v2 beta #49. I recommend you upgrade in test mode and confirm the workflow end to end in your test environment to then upgrade in live mode.
