### ISSUE TITLE
KYC status update failed. 'Bus named "messenger.bus.default" does not exist.'

### ISSUE THREAD

**Issue by RubenB** [stripe/stripe-mirakl-connector#61]
Hi 

We currently have an issue with KYC status updates from Stripe towards Mirakl.
The technical alert emails contain the following error:

message: | "[object] (App\\Message\\AccountUpdateMessage: {})"
-- | --
class: | App\Message\AccountUpdateMessage
retryCount: | 3
delay: | 25000
error: | Bus named "messenger.bus.default" does not exist.
exception: | {    "class": "Symfony\\Component\\Messenger\\Exception\\InvalidArgumentException",    "message": "Bus named \"messenger.bus.default\" does not exist.",    "code": 0,    "file": "/var/www/vendor/symfony/messenger/RoutableMessageBus.php:63",    "trace": [        "/var/www/vendor/symfony/messenger/RoutableMessageBus.php:54",        "/var/www/vendor/symfony/messenger/Worker.php:117",        "/var/www/vendor/symfony/messenger/Worker.php:81",        "/var/www/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:202",        "/var/www/vendor/symfony/console/Command/Command.php:255",        "/var/www/vendor/symfony/console/Application.php:1019",        "/var/www/vendor/symfony/framework-bundle/Console/Application.php:97",        "/var/www/vendor/symfony/console/Application.php:271",        "/var/www/vendor/symfony/framework-bundle/Console/Application.php:83",        "/var/www/vendor/symfony/console/Application.php:147",        "/var/www/bin/console:42"    ]}

We followed the docker instructions to set this up on AWS.
Any idea what could be the problem? 

Thanks!
Kind regards
Ruben

**Comment by youssef-stripe** [comment]
Looks like the app doesn't find a consumer for the AccountUpdateMessage sent to the queue. By default, these messages are sent to the following queues: operator_http_notification, update_login_link, update_kyc_status.

If you look at your [supervisord.conf](https://github.com/stripe/stripe-mirakl-connector/blob/master/examples/docker/app/config/supervisord.conf), did you keep the workers consuming these queues?
Any changes you did to the default Docker example?

**Comment by RubenB** [comment]
Also FYI, we are updated to 1.2.7 earlier this week. We had the same problem before the update.
These queues are still used in the supervisord.conf
`
[program:php-command-operator_http_notification]
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
command=php /var/www/bin/console messenger:consume operator_http_notification update_login_link update_kyc_status --time-limit=3600 --env=prod --quiet
`
operator_http_notification, update_login_link, update_kyc_status are unchanged. So this means that the queues are not available for consumtion? 
Dockerfile is unchanged. 

Is there another place where the "initialization" of the queues are executed?

**Comment by youssef-stripe** [comment]
@RubenB, still trying to reproduce, unsuccessfully so far. Could you please confirm the value of the following environment variables in your setup:
- MESSENGER_TRANSPORT_DSN
- APP_ENV

**Comment by RubenB** [comment]
It seemed that the APP_ENV contained `prd` instead of `prod`.
KYC statusses now update, thanks!

**Comment by youssef-stripe** [comment]
Glad to hear it's solved!
