### ISSUE TITLE
Non success response from Connect Account update risks webhook being disabled

### ISSUE THREAD

**Issue by christophersjchow** [stripe/stripe-mirakl-connector#62]
We have the webhook setup against Stripe Connect triggering for `account.updated` events. However we have a number of other Stripe Connect Custom accounts setup that sit outside the Mirakl use case. These accounts have updates occurring on them quite regularly triggering webhook events.

As the webhook responds with a 400 

```
This Stripe Account does not exist
```

there is a risk Stripe will disable the webhook. Can we return a 200 response similar to how the charge.updated/succeeded returns a 200 but simply says there's no `miraklOrderId`?

**Comment by youssef-stripe** [comment]
Good point, this is changed by e63a4cc.
