### ISSUE TITLE
key is a reserved keyword in SQL Server

### ISSUE THREAD

**Issue by eBusEntwHOFM** [stripe/stripe-mirakl-connector#66]
Hi there,

unfortunately we are currently unable to use `stripe-mirakl-connector` with Postgres, so we use SQL Server instead. In SQL Servie is `key` (which is a new column in `2.0.0`) one of the reserved keywords. It seams like the `doctrine` isn't able to properly escape it, so we are forced to patch  ´src/Entity/Config.php`

```
Index: src/Entity/Config.php
<+>UTF-8
===================================================================
--- src/Entity/Config.php	(revision 2ebee9da7b1daec213717ef19ae1f5e33d04da38)
+++ src/Entity/Config.php	(date 1613655841473)
@@ -23,7 +23,7 @@
     private $id;
 
     /**
-     * @ORM\Column(type="string", unique=true)
+     * @ORM\Column(name="[key]", type="string", unique=true)
      */
     private $key;
```
Would it be possible to add escape configuration to the doctrine?

Best regards

**Comment by youssef-stripe** [comment]
Thanks for flagging! This is fixed in v2.0.2.
