### ISSUE TITLE
Tried to bind parameter number 2101. SQL Server supports a maximum of 2100 parameters

### ISSUE THREAD

**Issue by eBusEntwHOFM** [stripe/stripe-mirakl-connector#68]
Hi there,

on our staging environment we have > 17.700 orders, because of integration tests. Looks like connector:dispatch:process-transfer cann't handle this number of orders, because it tries the save them all at once. So large number of parameters isn't supported by most of RDBMS.
```
\nSQLSTATE[IMSSP]: Tried to bind parameter number 2101.  SQL Server supports a maximum of 2100 parameters.\"},\"level\":400,\"level_name\":\"ERROR\",\"channel\":\"console\",\"datetime\":{\"date\":\"2021-02-21 08:30:19.202903\",\"timezone_type\":3,\"timezone\":\"UTC\"},\"extra\":[]}" channel=stdout iteration=0 job.command="php /var/www/bin/console connector:dispatch:process-transfer -q 2>&1" job.position=2 job.schedule="1-59/5
```

Best regards
@eBusEntwHOFM

**Comment by youssef-stripe** [comment]
Thanks for flagging @eBusEntwHOFM!

We implemented a change in v2.0.2 to persist new transfers 100 at a time instead of all at once.
