### ISSUE TITLE
Mirakl - Multiple stores/sellers per user

### ISSUE THREAD

**Issue by RubenB** [stripe/stripe-mirakl-connector#74]
Hi,

We are currently using version 1.2.7.
Does the connector support mulitple sellers/stores per user? 
Existing sellers are not able to complete the KYC process when they try to onboard with a second account that is linked to their main account.

Feature that I am referring to: https://help.mirakl.net/Customers/topics/Mirakl/mmp/Operator/manage_user_and_rights/store_users/managing_multiple_stores_per_user.html?Highlight=multi-seller

**Comment by youssef-stripe** [comment]
Hi @RubenB,

Currently you can only use a Stripe account for a single shop.

The seller can follow the onboarding link for each of their shop to create a new Stripe account for each. Note that they'll have to use a different email address or else Stripe will reuse the existing account. It doesn't have to be an entirely new address, they can use something like "name+shop1@example.com", "name+shop2@example.com", etc.

Still, we'll take this remark under advisement and will see if we can make reusing a single Stripe account for multiple shops possible in the future. Thanks for the feedback.

PS: I strongly recommend you upgrade to v2.1.0 as we improved the workflows drastically in version 2 of the connector.

**Comment by RubenB** [comment]
Hi @youssef-stripe 

You are welcome!
Thanks for your clarification. 

We will take a look at the possibility to upgrade to V2.x.x
