### ISSUE TITLE
Subscription Transfer failed

### ISSUE THREAD

**Issue by juanbarrios18** [stripe/stripe-mirakl-connector#76]
Hi @youssef-stripe 

We are currently using the version 1.2.7.

When the connector tries to execute the subscription transfer (Connected account > main account) stripe sends the following error message: **"This value must be greater than or equal to 1."**. This value comes from the Mirakl API **/api/invoices summary.total_subscription_incl_tax** and is a negative value.

Checking the stripe [API](https://stripe.com/docs/api/transfers/create), they have validation in the field AMOUNT. "A positive integer in cents representing how much to transfer."

On the other hand, the [source code](https://github.com/stripe/stripe-mirakl-connector/blob/master/src/Factory/StripeTransferFactory.php) (line 472) of the connector has a validation of this amount. the amount has to be greater or equal than 0, even in the newest versions(2.1.0)

How can we execute the subscription transfer¿? 

Thanks

**Comment by youssef-stripe** [comment]
Hi @juanbarrios18,

You are correct, the amount should be parsed into a positive value before being checked and persisted, by calling gmp_abs on the amount for example.

We will fix this in v2.1.1 as soon as possible.

Thanks for flagging this.

**Comment by youssef-stripe** [comment]
This is now fixed in v2.1.1.

Thanks again for reporting this issue!
