### ISSUE TITLE
Add config option to disable negative debits for connected accounts

### ISSUE THREAD

**Issue by christophersjchow** [stripe/stripe-mirakl-connector#78]
During Stripe Connect onboarding the connect account is configured with Debit Negative balances as on. Could we add an environment variable to disable this for created Connect accounts?

**Comment by youssef-stripe** [comment]
Noting here our conclusions so far based on our discussions:

* There's no proper way of informing Mirakl that Stripe debited a negative balance without skewing with the sales numbers (e.g. if we were to create a manual invoice in Mirakl for the amount debited by Stripe).
* Building some custom logic within the connector to handle the discrepancy between the Mirakl invoices and the Stripe balance would be too scrappy and not a long term solution.
* Based on the above, the best way to handle seller debt is to disable auto-debit until Mirakl offers a way to properly record this debit.
* There are then two scenarios:
1. new orders are created for this seller and eventually the debt is paid.
2. the seller stops selling on the marketplace and the operator will have to pursue recovering the debt directly with them outside of Stripe/Mirakl.

Next step would be to release a patch to disable auto-debit on the new Stripe accounts + add a migration to backfill existing accounts.

**Comment by youssef-stripe** [comment]
Negative balance auto debit now defaults to false in v3.0.0 (see #97).
