### ISSUE TITLE
Store the Mirakl shop id against metadata of Connect Account

### ISSUE THREAD

**Issue by christophersjchow** [stripe/stripe-mirakl-connector#84]
We have a use case of notifying a seller that a change has been made to their Stripe Connect account. To achieve this we intend to leverage webhooks when a Connect account is updated.

However the only location that the mapping between a seller's shop id and the Connect account id is within the connector's database. Ideally this id would be stored against the Connect account as metadata so it can be used when responding to webhooks of `account.external_account.update`.

**Comment by youssef-stripe** [comment]
This has been released under v2.1.3.

Thanks for the contribution and for your patience.
