### ISSUE TITLE
Transfer fails due to account in the UK

### ISSUE THREAD

**Issue by RubenB** [stripe/stripe-mirakl-connector#87]
Hi

Currently we have the problem that a transfer is blocked to the UK. The stripe account that is used has EU top-ups activated.
The message is: **"Stripe does not currently support users of EU Top-ups like your platform to make transfers to connected accounts based in the UK."**

Do you know if there is a way to keep the method of separate charges and transfers when also being able to pay out UK sellers? Or is the only solution to implement destination charges?

Currently the connector is putting the transfers to the UK account on FAILED and we do not have an easy way clean that data. The current solution is that the financial department will handle the UK account manually. What do you propose?

**Comment by youssef-stripe** [comment]
Hi @RubenB,

Please write in to support@stripe.com and cc mirakl-connector@stripe.com with request IDs to help with the investigation.

Note that handling failures manually outside the connector is not recommended and could lead to duplicates.

**Comment by RubenB** [comment]
Hi Youssef

Thanks for the feedback
