### ISSUE TITLE
Payment failed never informs Mirakl

### ISSUE THREAD

**Issue by thearegee** [stripe/stripe-mirakl-connector#95]
Hello,

When Stripe rejects a payment for whatever reason it never informs Mirakl, this means it sits in a pending state. After 30 days Mirakl cancels and clears these blocked orders. However this is a real problem for a seller, they don't know the status as they can't see in an operators Stripe account.

By reviewing the various order workflows in Mirakl, they can see that when a payment is refused, the order will be set to the "Canceled" status. The technical name for the "Canceled" order status is `CANCELED`.

However, to cancel orders via API, you'll want to pass a value of `REFUSED` to the `payment_status` node in the PA01 API.

There are two relevant order workflows: Pay on Acceptance and Pay on Shipment. Both of these order workflows will trigger the OR15 email notification once the order moves from the "Debit in Progress" status to the "Canceled" status. So, even if you manually refuse the payment by invoking the PA01 API yourself, the OR15 email notification will still be sent out.

You can see here the notifications is ready in Mirakl:
![image](https://user-images.githubusercontent.com/8751165/153007492-ecedc71e-5858-44d9-80b6-d334cfe0d42a.png)

However it never gets triggered as Stripe Mirakl connector never informs Mirakl of a failed payment, so not only do our sellers not know about the problem but neither do the customers.

This can be solved by calling PA01 with the `REFUSED` status on failed payment.

**Comment by youssef-stripe** [comment]
Hello @thearegee,

A failed payment isn't always final. Operators could allow customers to try again, maybe with a different payment method.
Operators would need a way to tell the connector that this is the final attempt and that it needs to call PA01 if this attempt fails. If the operator is able to tell that to the connector, they can very well call PA01 without having to rely on the connector, don't you think?

**Comment by thearegee** [comment]
I don't think that makes sense because the process is asynchronous and the operator doesn't tell the connector anything, the connector works on a cron talking directly to Mirakl. It collects orders after they have been created so the flow works like this:

* Put a holding payment on the stripe request
* Order is created in Mirakl
* Stripe Mirakl connector picks up the order
* Tries to process payment
* Payment fails
* Holding payment is marked as failed in stripe
* Mirakl things the payment is pending

As fay as the user is aware they have placed an order. With what you're saying you would need one of the two:
* Hold off from leaving checkout flow until the order creation has been processed by the connector and failed by Stripe. Then prompt them to try another payment method. This could be several minutes
* Have a section where you collect all the failed payments and ask people to come back later to complete the payment and try another but by this point the products might have sold out

There is of course already validation in the creating of a payment request in stripe, this is for creating the order which is a different flow and potential error

**Comment by youssef-stripe** [comment]
> Tries to process payment

Not sure I understand this step. Which workflow are we talking about?

**Comment by thearegee** [comment]
So for a flow like this:
* With an order you create a payment intent: https://stripe.com/docs/payments/payment-intents 
* Then an order is created 
* Stripe mirakl connector on a cron then picks up the orders
* Then payment is authorised and captured

Here it is in stripe:
<img width="208" alt="image" src="https://user-images.githubusercontent.com/8751165/157423053-0d534155-4387-42c2-9dcb-ce5a1f1e8f8d.png">

If there is a failure at this point from the connector there is no way for Mirakl to know. So the order gets stuck in a pending status for 30 days

**Comment by youssef-stripe** [comment]
The payment is authorized before the connector picks up the order so I assume you mean what happens if the **capture** fails then, correct?
Unless you wait too long (> 7 days), the capture shouldn't fail and you should have rules in place to prevent orders from being accepted/rejected after 7 days, e.g. by auto rejecting orders still not accepted on the 6th day.
Sorry if I'm still missing the use case you're trying to pinpoint. Maybe if you could give an example of what you mean by failure?

**Comment by thearegee** [comment]
> The payment is authorized before the connector picks up the order so I assume you mean what happens if the capture fails then, correct?

Correct, its a failure after the order is created

> Unless you wait too long (> 7 days), the capture shouldn't fail and you should have rules in place to prevent orders from being accepted/rejected after 7 days, e.g. by auto rejecting orders still not accepted on the 6th day.

This is already in place.

@youssef-stripe thank you for looking in, I will work now on building you an example with some data thats removed anything sensitive

**Comment by youssef-stripe** [comment]
Closing this issue as it's been inactive for almost 2 months.
