### ISSUE TITLE
Seller onboarding status is not getting updated

### ISSUE THREAD

**Issue by TechyChap** [stripe/stripe-mirakl-connector#98]
I've got the /api/public/webhook/sellers webhook configured to listen to account.updated in Stripe as per https://stripe.com/docs/plugins/mirakl/configuration#add-a-stripe-webhook-endpoint-for-connected-accounts

I can see the new sellers appearing under the "connected accounts" but my hook is not getting called. There seems to be no events in the stripe logs.

The S07 API call never gets called.

**Comment by youssef-stripe** [comment]
Hi @TechyChap,

Please [contact the Stripe support](https://support.stripe.com/contact) directly for troubleshooting technical issues.


Thanks

**Comment by TechyChap** [comment]
I was wondering if the documentation was wrong? e.g. capturing the wrong event

**Comment by youssef-stripe** [comment]
`account.updated` is the right event. Just make sure to configure the webhook ending with "sellers" to listen to connected accounts events:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/47321947/157426770-ee6fede5-926a-406d-8298-23106545f991.png">

**Comment by youssef-stripe** [comment]
Also make sure to set the signing key for this webhook under the `STRIPE_SELLERS_WEBHOOK_SECRET` var.

**Comment by youssef-stripe** [comment]
Tip: account.updated events being fired at the connected account level, you won't find them in your platform account's events. You have to log to the connected account's dashboard and then go to events:
<img width="1641" alt="image" src="https://user-images.githubusercontent.com/47321947/157427500-9ee2b662-2266-4d6c-8e04-88831e993286.png">

**Comment by TechyChap** [comment]
Thanks Youssef. It was the "Listen to events on Connected accounts" tick box that had been missed. Have corrected that now.

![image](https://user-images.githubusercontent.com/66316732/157431958-a9099835-9e05-4ef9-aa27-77265fcd55a9.png)

The documentation kind of makes the assumption you know what settings to enter. Step 2 could be clearer. Or even explicitly add a step that says "tick the box"

![image](https://user-images.githubusercontent.com/66316732/157432279-ae5eb7c4-8ca8-4854-a075-d545c37300d4.png)
